---
- name: Install vdsm-prometheus COPR repo on EPEL
  get_url: url={{ vdsm_prometheus_epel_repo_url }} dest=/etc/yum.repos.d/vdsm-prometheus.repo
  retries: 5
  delay: 10
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: Install vdsm-prometheus COPR repo on Fedora
  get_url: url={{ vdsm_prometheus_fedora_repo_url }} dest=/etc/yum.repos.d/vdsm-prometheus.repo
  retries: 5
  delay: 10
  when: ansible_distribution == 'Fedora'

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ vdsm_prometheus_repo_gpg_key_url }}"
    state: present

- name: Install vdsm-prometheus
  yum: name=vdsm-prometheus state=latest

- name: Create vdsm-prometheus configuration dorectory
  file: path=/etc/systemd/system/vdsm-prometheus.service.d/ state=directory

- name: Copy vdsm-prometheus configuration
  template: src=10-vdsm-prometheus.conf dest=/etc/systemd/system/vdsm-prometheus.service.d/10-vdsm-prometheus.conf owner=root group=root force=yes

- name: Reload vdsm-prometheus service
  command: systemctl daemon-reload

- name: Open port 8181
  shell: iptables -D INPUT -p tcp --dport 8181 -j ACCEPT  || true && iptables -I INPUT -p tcp --dport 8181 -j ACCEPT && service iptables save

- name: Enable and start vdsm-prometheus service
  service: name=vdsm-prometheus enabled=yes state=restarted
